#!/bin/bash
# Claude Plugin Toolkit - Setup Script
# Adds all curated marketplaces and installs essential plugins

echo "=== Claude Plugin Toolkit Setup ==="
echo ""

# Step 1: Add marketplaces
echo "[1/2] Adding plugin marketplaces..."
echo ""
echo "Run these commands inside Claude Code:"
echo ""
echo "  /plugin marketplace add anthropics/claude-plugins-official"
echo "  /plugin marketplace add ananddtyagi/cc-marketplace"
echo "  /plugin marketplace add davepoon/buildwithclaude"
echo "  /plugin marketplace add ComposioHQ/awesome-claude-plugins"
echo ""

# Step 2: Install priority plugins
echo "[2/2] Priority plugins to install:"
echo ""
echo "--- OFFICIAL (must-have) ---"
echo "  /plugin install code-review@claude-plugins-official"
echo "  /plugin install security-guidance@claude-plugins-official"
echo "  /plugin install frontend-design@claude-plugins-official"
echo "  /plugin install context7@claude-plugins-official"
echo "  /plugin install commit-commands@claude-plugins-official"
echo "  /plugin install claude-md-management@claude-plugins-official"
echo "  /plugin install feature-dev@claude-plugins-official"
echo "  /plugin install typescript-lsp@claude-plugins-official"
echo "  /plugin install playwright@claude-plugins-official"
echo "  /plugin install pr-review-toolkit@claude-plugins-official"
echo "  /plugin install code-simplifier@claude-plugins-official"
echo "  /plugin install hookify@claude-plugins-official"
echo "  /plugin install claude-code-setup@claude-plugins-official"
echo ""
echo "--- LEGAL / COMPLIANCE ---"
echo "  /plugin install legal-advisor@cc-marketplace"
echo "  /plugin install legal-compliance-checker@cc-marketplace"
echo "  /plugin install compliance-automation-specialist@cc-marketplace"
echo ""
echo "--- RESEARCH / INVESTIGATION ---"
echo "  /plugin install trend-researcher@cc-marketplace"
echo "  /plugin install agents-specialized-domains@buildwithclaude"
echo ""
echo "--- DOCUMENT PROCESSING ---"
echo "  /plugin install vision-specialist@cc-marketplace"
echo "  /plugin install all-skills@buildwithclaude  # includes pdf, docx, xlsx, pptx"
echo ""
echo "--- CODE QUALITY ---"
echo "  /plugin install audit@cc-marketplace"
echo "  /plugin install double-check@cc-marketplace"
echo "  /plugin install audit-project@ComposioHQ/awesome-claude-plugins"
echo ""
echo "--- WEB DEV ---"
echo "  /plugin install web-dev@cc-marketplace"
echo "  /plugin install senior-frontend@ComposioHQ/awesome-claude-plugins"
echo "  /plugin install nextjs-expert@buildwithclaude"
echo ""
echo "--- GIT WORKFLOWS ---"
echo "  /plugin install fix-github-issue@cc-marketplace"
echo "  /plugin install ship@ComposioHQ/awesome-claude-plugins"
echo ""
echo "--- AUTOMATION ---"
echo "  /plugin install ultrathink@cc-marketplace"
echo "  /plugin install lyra@cc-marketplace"
echo ""
echo "=== Setup Complete ==="
echo "Browse all available plugins with: /plugin"
